#!/bin/bash

Path="`dirname \"$0\"`"              # relative
Path="`( cd \"$Path\" && pwd )`"  # absolutized and normalized

sudo apt-get install gtk-doc-tools python-cairo-dev python-numpy python-pip python-scipy python-glade2 python-gtkglext1
sudo pip install -U rdflib
